# -*- coding: utf-8 -*-
"""Fab-Gaurav.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VLXtcOUBBLUizRdlUhP0QKsmzrdc04xE
"""

num=int(input("Enter the number : "))
if (num % 2) == 0 :
  print(num, "is an even number")
else :
  print(num, "is an odd number")
